In [22]:
#importamos las variables
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

# Cargamos el DataSet

In [24]:
iris = load_iris(as_frame=True)

In [25]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [26]:
# Convertimos los datos en DataFrame
dfIris = iris.frame
dfIris.head(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0

In [27]:
dfIris.tail(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [28]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [29]:
#Cambiamos la columna de Target por Especie
dfIris.rename(columns={"target" : "species"}, inplace=True)

In [30]:
#Remplazamos los valores numericos por las especies
dfIris["species"] = dfIris["species"].map(
    {
        0: "setosa",
        1: "versicolor",
        2: "virginica"
    }
)

## Variables predictoras y Variable objetivo

X (Variables predictoras) son aquellas que me permiten hacer la prediccion
y (objetivo) Lo que quiero predecir

In [31]:
#Variables predictoras
X = dfIris.drop(columns=["species"])

In [32]:
#Variable objetivo
y = dfIris["species"]

In [33]:
print("----Variables predictoras----")
print(X.columns)
print("----Variable Objetivo -----")
print(y.name)

----Variables predictoras----
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')
----Variable Objetivo -----
species

## División del conjunto de datos

*Training Set:* Datos para entrenamiento.

*Testing Set:* Datos no vistos por el modelo, para prueba.

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X, #Variables predictoras
    y, #Variable objetivo,
    test_size = 0.20,
    random_state=42,
    stratify=y
)

In [35]:
print("X_train: ", X_train.shape)
print("X_test: ", X_test.shape)
print("--------------------------")
print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

X_train:  (120, 4)
X_test:  (30, 4)
--------------------------
y_train:  (120,)
y_test:  (30,)

## Escalado de las variables

In [36]:
scaler = StandardScaler()

In [37]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [38]:
print("-----------Datos sin escalar------------")
print(X_train.head(5))
print("-----------Escalados-----------")
print(X_train_scaled[:5])

-----------Datos sin escalar------------
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
106                4.9               2.5                4.5               1.7
76                 6.8               2.8                4.8               1.4
9                  4.9               3.1                1.5               0.1
89                 5.5               2.5                4.0               1.3
-----------Escalados-----------
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]

## Entrenamiento del modelo

In [39]:
#Creamos una instancia del algoritmo
modelo = KNeighborsClassifier(
    n_neighbors = 3
)

In [40]:
#Entrenamos con los datos de entrenamiento
modelo.fit(
    X_train_scaled,
    y_train
)

KNeighborsClassifier(n_neighbors=3)

## Predicción con los datos de prueba

In [41]:
prediccion = modelo.predict(X_test_scaled)

In [42]:
pd.DataFrame({
    "Especie real" : y_test.values,
    "Especie predicha" : prediccion
}).head(20)

   Especie real Especie predicha
0        setosa           setosa
1     virginica        virginica
2    versicolor       versicolor
3    versicolor       versicolor
4        setosa           setosa
5    versicolor       versicolor
6        setosa           setosa
7        setosa           setosa
8     virginica        virginica
9    versicolor       versicolor
10    virginica        virginica
11    virginica        virginica
12    virginica        virginica
13   versicolor       versicolor
14       setosa           setosa
15       setosa           setosa
16       setosa           setosa
17   versicolor       versicolor
18   versicolor       versicolor
19    virginica       versicolor

## EVALUACIÓN DEL MODELO

*Las metricas a usar son: accuracy, precision, recall, f1-score

In [43]:
#Accuracy
accuracy = accuracy_score(y_test, prediccion)

In [44]:
print ( f"Accuracy / Exactitud del modelo es:  { accuracy: .4f}")

Accuracy / Exactitud del modelo es:   0.9333

In [45]:
#Matriz de confusión
matrizConfusion = confusion_matrix(y_test, prediccion)
matrizConfusion_df = pd.DataFrame(
    matrizConfusion,
    index = modelo.classes_,
    columns = modelo.classes_
)

In [46]:
matrizConfusion_df

            setosa  versicolor  virginica
setosa          10           0          0
versicolor       0          10          0
virginica        0           2          8

In [48]:
# Matriz de metricas : Clasification Report
print (classification_report(y_test, prediccion))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30